services:
  - type: web
    name: epub-translator
    env: node
    plan: free
    buildCommand: npm cache clean --force && rm -rf .next && npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_DEEPSEEK_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.17.0
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - next.config.js
        - tsconfig.json
        - postcss.config.js
        - tailwind.config.js
