services:
  - type: web
    name: epub-translator
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_DEEPSEEK_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
